#nullable enable

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabbedTortoiseGit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> RecentRepos {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["RecentRepos"]));
            }
            set {
                this["RecentRepos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Size {
            get {
                return ((global::System.Drawing.Size)(this["Size"]));
            }
            set {
                this["Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Maximized {
            get {
                return ((bool)(this["Maximized"]));
            }
            set {
                this["Maximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> StartupRepos {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["StartupRepos"]));
            }
            set {
                this["StartupRepos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxRecentRepos {
            get {
                return ((int)(this["MaxRecentRepos"]));
            }
            set {
                this["MaxRecentRepos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> TabContextMenuGitActions {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["TabContextMenuGitActions"]));
            }
            set {
                this["TabContextMenuGitActions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfirmOnClose {
            get {
                return ((bool)(this["ConfirmOnClose"]));
            }
            set {
                this["ConfirmOnClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FastSubmoduleUpdateInitChecked {
            get {
                return ((bool)(this["FastSubmoduleUpdateInitChecked"]));
            }
            set {
                this["FastSubmoduleUpdateInitChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FastSubmoduleUpdateRecursiveChecked {
            get {
                return ((bool)(this["FastSubmoduleUpdateRecursiveChecked"]));
            }
            set {
                this["FastSubmoduleUpdateRecursiveChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FastSubmoduleUpdateForceChecked {
            get {
                return ((bool)(this["FastSubmoduleUpdateForceChecked"]));
            }
            set {
                this["FastSubmoduleUpdateForceChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FastSubmoduleUpdateMaxProcesses {
            get {
                return ((int)(this["FastSubmoduleUpdateMaxProcesses"]));
            }
            set {
                this["FastSubmoduleUpdateMaxProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenStartupReposOnReOpen {
            get {
                return ((bool)(this["OpenStartupReposOnReOpen"]));
            }
            set {
                this["OpenStartupReposOnReOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FastSubmoduleUpdateShowOnlyModifiedSubmodulesChecked {
            get {
                return ((bool)(this["FastSubmoduleUpdateShowOnlyModifiedSubmodulesChecked"]));
            }
            set {
                this["FastSubmoduleUpdateShowOnlyModifiedSubmodulesChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FastSubmoduleUpdateCheckModifiedSubmodulesByDefault {
            get {
                return ((bool)(this["FastSubmoduleUpdateCheckModifiedSubmodulesByDefault"]));
            }
            set {
                this["FastSubmoduleUpdateCheckModifiedSubmodulesByDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FastFetchTagsChecked {
            get {
                return ((bool)(this["FastFetchTagsChecked"]));
            }
            set {
                this["FastFetchTagsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FastFetchPruneChecked {
            get {
                return ((bool)(this["FastFetchPruneChecked"]));
            }
            set {
                this["FastFetchPruneChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FastFetchMaxProcesses {
            get {
                return ((int)(this["FastFetchMaxProcesses"]));
            }
            set {
                this["FastFetchMaxProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FastFetchShowProgress {
            get {
                return ((bool)(this["FastFetchShowProgress"]));
            }
            set {
                this["FastFetchShowProgress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeveloperSettingsEnabled {
            get {
                return ((bool)(this["DeveloperSettingsEnabled"]));
            }
            set {
                this["DeveloperSettingsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowHitTest {
            get {
                return ((bool)(this["ShowHitTest"]));
            }
            set {
                this["ShowHitTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseToSystemTray {
            get {
                return ((bool)(this["CloseToSystemTray"]));
            }
            set {
                this["CloseToSystemTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font ModifiedTabFont {
            get {
                return ((global::System.Drawing.Font)(this["ModifiedTabFont"]));
            }
            set {
                this["ModifiedTabFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ModifiedTabFontColor {
            get {
                return ((global::System.Drawing.Color)(this["ModifiedTabFontColor"]));
            }
            set {
                this["ModifiedTabFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IndicateModifiedTabs {
            get {
                return ((bool)(this["IndicateModifiedTabs"]));
            }
            set {
                this["IndicateModifiedTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int CheckForModifiedTabsInterval {
            get {
                return ((int)(this["CheckForModifiedTabsInterval"]));
            }
            set {
                this["CheckForModifiedTabsInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseWindowOnLastTabClosed {
            get {
                return ((bool)(this["CloseWindowOnLastTabClosed"]));
            }
            set {
                this["CloseWindowOnLastTabClosed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-01-01")]
        public global::System.DateTime LastUpdatePromptTime {
            get {
                return ((global::System.DateTime)(this["LastUpdatePromptTime"]));
            }
            set {
                this["LastUpdatePromptTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteReposJsonString {
            get {
                return ((string)(this["FavoriteReposJsonString"]));
            }
            set {
                this["FavoriteReposJsonString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font NormalTabFont {
            get {
                return ((global::System.Drawing.Font)(this["NormalTabFont"]));
            }
            set {
                this["NormalTabFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color NormalTabFontColor {
            get {
                return ((global::System.Drawing.Color)(this["NormalTabFontColor"]));
            }
            set {
                this["NormalTabFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KeyboardShortcutsString {
            get {
                return ((string)(this["KeyboardShortcutsString"]));
            }
            set {
                this["KeyboardShortcutsString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfirmFasterFetch {
            get {
                return ((bool)(this["ConfirmFasterFetch"]));
            }
            set {
                this["ConfirmFasterFetch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FasterSubmoduleUpdateInitChecked {
            get {
                return ((bool)(this["FasterSubmoduleUpdateInitChecked"]));
            }
            set {
                this["FasterSubmoduleUpdateInitChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FasterSubmoduleUpdateRecursiveChecked {
            get {
                return ((bool)(this["FasterSubmoduleUpdateRecursiveChecked"]));
            }
            set {
                this["FasterSubmoduleUpdateRecursiveChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FasterSubmoduleUpdateForceChecked {
            get {
                return ((bool)(this["FasterSubmoduleUpdateForceChecked"]));
            }
            set {
                this["FasterSubmoduleUpdateForceChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FasterSubmoduleUpdateMaxProcesses {
            get {
                return ((int)(this["FasterSubmoduleUpdateMaxProcesses"]));
            }
            set {
                this["FasterSubmoduleUpdateMaxProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FasterSubmoduleUpdateAllSubmodules {
            get {
                return ((bool)(this["FasterSubmoduleUpdateAllSubmodules"]));
            }
            set {
                this["FasterSubmoduleUpdateAllSubmodules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomActionsString {
            get {
                return ((string)(this["CustomActionsString"]));
            }
            set {
                this["CustomActionsString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckTortoiseGitOnPath {
            get {
                return ((bool)(this["CheckTortoiseGitOnPath"]));
            }
            set {
                this["CheckTortoiseGitOnPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShouldShowChangelog {
            get {
                return ((bool)(this["ShouldShowChangelog"]));
            }
            set {
                this["ShouldShowChangelog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowChangelogOnUpdate {
            get {
                return ((bool)(this["ShowChangelogOnUpdate"]));
            }
            set {
                this["ShowChangelogOnUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int SplitLayoutSplitterDistance {
            get {
                return ((int)(this["SplitLayoutSplitterDistance"]));
            }
            set {
                this["SplitLayoutSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideReferencesDisplay {
            get {
                return ((bool)(this["HideReferencesDisplay"]));
            }
            set {
                this["HideReferencesDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\TortoiseGit\\bin\\TortoiseGitProc.exe")]
        public string TortoiseGitProcExeLocation {
            get {
                return ((string)(this["TortoiseGitProcExeLocation"]));
            }
            set {
                this["TortoiseGitProcExeLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TreatUninitializedSubmodulesAsModified {
            get {
                return ((bool)(this["TreatUninitializedSubmodulesAsModified"]));
            }
            set {
                this["TreatUninitializedSubmodulesAsModified"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastVersion {
            get {
                return ((string)(this["LastVersion"]));
            }
            set {
                this["LastVersion"] = value;
            }
        }
    }
}
